server:
  port: 8086

spring:
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss


bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}